/*DROP TABLE IF EXISTS submissions;*/

CREATE TABLE IF NOT EXISTS submissions (
  id INTEGER PRIMARY KEY,
  userID TEXT,
  sumE INTEGER NOT NULL,
  sumI INTEGER NOT NULL,
  sumS INTEGER NOT NULL,
  sumN INTEGER NOT NULL,
  sumT INTEGER NOT NULL,
  sumF INTEGER NOT NULL,
  sumJ INTEGER NOT NULL,
  sumP INTEGER NOT NULL,
  personalityType TEXT
);
